                 
                                🔰//Minggu,16 Januari 2022🔰
                
//Model : Script Bot Whatsapp
//Versi : 8.0.1

//Informasi :
// Wajib Subs Chanel OwnerNya
// Dilarang Jual Script Inj
// Jangan Hapus THx To
// Berikut Cara² Menambah Fitur
//=============================================

1). CARA MENAMBAH FITUR SHOP

• BUKA FOLDER SHOP 
• LALU BUAT FILE BARU, CONTOH ML.JS
• LALU BUAT CONST NYA CONTOH, (const ml =`)
• LALU KASIH LIST NYA DAN DI AKHIR DENGAN (`)
• DI PALING BAWAH KALIAN KASIH [ exports.logo = logo ]
• SETELAH ITU BUKA SIMPLE.JS 
• LALU KASIH CONST FOLDER YANG TADI CONTOH : const { Nama Const Nya } = require('./shop/Nama Const Nya')
• LALU BUAT CASE, CONTOH :
- case 'jaslog':
simple.updatePresence(from, Presence.recording)
img =  fs.readFileSync('./poto/YENI.jpg')
tod = `${logo}`
but = [
{ buttonId: `${prefix}owner`, buttonText: { displayText: 'OWNER' }, type: 1 }, 
{ buttonId: `${prefix}sewabot`, buttonText: { displayText: 'SEWABOT' }, type: 1 }, 
]arguments
 sendButImage(from, tod, faketeks, img, but) 
break
 
• Lalu Coba Deh

2). Cara Ubah Nama Bot & Owner

• Buka Setting Json 
• Lalu Cari ownername : "Nama Lu"
• Lalu Ubah Yang Nama Lu Nya Jadi Nama Kamu
• Cari botname : "Nama Bot Lu"
• Lalu Ubah Nama Bot Lu nya Jadi Nama Bot Kamu
• Dan simpan

//==== [ JANGAN MELANGGAR PROSEDUR YANG ADA ] =====
